services:
  tiktokarchive-blazor:
    image: ${DOCKER_REGISTRY-}tiktokarchiveblazor
    build:
      context: .
      dockerfile: TikTokArchive.Web/Dockerfile
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - OpenSearch:Url=http://opensearch:9200
      - RABBITMQ_CONNECTION_STRING=amqp://guest:guest@rabbitmq:5672
      - STT_PROVIDER=None
      - WHISPER_URL=http://whisper:9000
      - WHISPER_MODEL=base
    volumes:
      - ./media:/media
    depends_on:
      - opensearch
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  whisper:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    volumes:
      - whisper_models:/root/.cache/whisper

  opensearch:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch_data:/usr/share/opensearch/data


volumes:
  opensearch_data:
  rabbitmq_data:
  whisper_models:
